---
title: "Producción I"
author:
  - name: "Ing. Sebastián Blandón Londoño"
    orcid: 0000-0002-0513-3860
    url: https://www.linkedin.com/in/sebastian-blandon/
    email: "s.blandon@utp.edu.co"
    affiliation: "Universidad Tecnológica de Pereira"
format:
  revealjs:
    margin: 0.05
    self-contained: true
    chalkboard: false
    theme: [simple, diapositiva.scss]
    wrap: auto
    progress: true
    toc: false
    toc-depth: 5
    logo: logo_utp2.png
    footer: "Ingeniería Industrial | Facultad de Ciencias Empresariales"
    menu:
      numbers: false
    slide-level: 4
    show-slide-number: speaker
    touch: true
    incremental: true
    preview-links: auto
    link-external-newwindow: true
    hide-inactive-cursor: true
    hide-cursor-time: 1500
    slide-tone: false
    pointer:
      color: 'red'
      key: 'q'
      pointerSize: 32
      alwaysVisible: false
    confetti:
      particleCount: 150
      angle: 90
      spread: 360
      startVelocity: 25
      gravity: 0.65
      drift: 0
      ticks: 400
      colors: ["#0366fc", "#f54281", "#1fd14f"]
      scalar: 0.7
    spotlight:
      toggleSpotlightOnMouseDown: false
      spotlightOnKeyPressAndHold: 18
      useAsPointer: false
revealjs-plugins:
  - pointer
  - confetti
editor: 
  markdown: 
    wrap: 72
---

# Introducción

## Presentación

### ¿Para qué sirve este curso?

## Contenido

## Evaluación

::: columns
::: {.column width="25%"}
**Módulo I (30%)**

\- Parcial (25%)

\- Actividades en clase (5%)
:::

::: {.column width="25%"}
**Módulo II (20%)**

\- Parcial (15%)

\- Actividades en clase (5%)
:::

::: {.column width="25%"}
**Módulo III (20%)**

\- Parcial (15%)

\- Actividades en clase (5%)
:::

::: {.column width="25%" .small-text}
**Módulo IV y Actividades Complementarias (30%)**

\- Lectura y presentación de artículo (5%)

\- Dashboard OEE (15%)

\- Taller de optimización en AMPL (10%)
:::
:::

## Recursos guía


## Herramientas de gestión del tiempo

### Google Calendar

### Google Tasks

### Microsoft OneNote

## Repaso de Investigación de Operaciones

### ¿Qué es la investigación de operaciones?

### Modelamiento matemático

### Optimización

### Software de optimización

## Elementos de AMPL

### Archivo mod

### Archivo dat

# Módulo I

::: notes
No olvidar saludar
:::

## Generalidades

### Origen elemental

### Historia

#### Revoluciones industriales

#### Personajes importantes

### Ciclo de vida del producto

### Sostenibilidad y sustentabilidad

## Ingeniería de sistemas de producción

### Categorización

### Sistemas de producción

### Distribución en planta

### Procesos industriales

#### Procesos continuos

#### Procesos discretos

### Diseño del proceso

### Parámetros básicos de los sistemas de producción

#### Capacidad

#### Tiempo de ciclo

### Little's Law

### Producción y lotes de transferencia

## Planeación de la capacidad de producción

### Análisis de la capacidad

### Punto de equilibrio

### Overall Equipment Efficiency (OEE)

### Theory of Constraints (TOC)

#### Critical Path Method

# Módulo II - Balanceo de líneas de producción

## Procesos, procedimientos, actividades, tareas, operaciones

## Líneas de producción

## Sistemas de ensamble

### Clasificación

### Tipos de problemas de ensamble

## Balanceo de líneas de ensamble

### Terminología

### Takt Time

### SALBP

#### SALBP-1

#### SALBP-2

#### SALBP-E

### MOALBP

### UALBP

#### UALBP-1

#### UALBP-2

# Módulo III - Secuenciamiento de tareas

## Production Engineering

## Terminología

## Job Scheduling

## Clasificación del taller

### Single machine

### Parallel machines

### Flow Shop

### Job Shop

### Flexible Flow Shop

### Flexible Job Shop

## Job Scheduling Parameters

## Dispatch Rules

## Dispatch Rules - Performance Measures

### Assotiated to jobs

### Assotiated to machines

## Nomenclaturas de problemas

## Some Scheduling Jobs types...

### Single Machine Scheduling

### Parallel Machines Scheduling

### Flow Shop Scheduling

### Job Shop Scheduling

# Módulo IV - Manufactura esbelta y herramientas tecnológicas

## Mejoramiento continuo

### Just in Time

### 5s

### Kaizen

### SMED

### Poka Yoke

### Six Sigma

#### Lean Six Sigma

## Herramientas empresariales

### Sistemas de información

### Analítica de datos

#### Dashboards

#### Modelos predictivos

#### Modelos 
